export type InputRecorderOptions = {

  /**
   * @description Whether to ignore input events generated by software processes.
   * If `true`, only hardware/driver input events will be treated. Otherwise,
   * all input events will be treated. Defaults to `false`.
   */
  ignoreInjected?: boolean;

};
