
declare module "@napi/actionify" {
  import type { Position } from "../types/position/position.type";
  import type { ScreenInfo } from "../types/screen-info/screen-info.type";
  import type { WindowInfo } from "../types/window-info/window-info.type";
  import type { Color } from "../types/color/color.type";
  import type { MatchRegion } from "../types/match-region/match-region.type";
  const value: {
    getCursorPos: Position;
    setCursorPos: (x: number, y: number) => void;
    leftClickDown: () => void;
    leftClickUp: () => void;
    rightClickDown: () => void;
    rightClickUp: () => void;
    mouseWheelScrollDown: (scrollAmount?: number) => void;
    mouseWheelScrollUp: (scrollAmount?: number) => void;
    mouseWheelPressDown: () => void;
    mouseWheelPressUp: () => void;
    mouseExtraButtonDown: (index: 1 | 2) => void;
    mouseExtraButtonUp: (index: 1 | 2) => void;
    keyPressDown: (keyCode: number) => void;
    keyPressUp: (keyCode: number) => void;
    typeUnicodeCharacter: (character: string) => void;
    getAvailableScreens: () => ScreenInfo[];
    startInputEventListener: (callback: Function) => void;
    stopInputEventListener: () => void;
    startWindowEventListener: (callback: Function) => void;
    stopWindowEventListener: () => void;
    cleanResources: () => void;
    listWindows: () => Array<WindowInfo>;
    getWindowById: (windowId: number) => WindowInfo | undefined;
    focusWindow: (windowId: number) => boolean;
    restoreWindow: (windowId: number) => boolean;
    minimizeWindow: (windowId: number) => boolean;
    maximizeWindow: (windowId: number) => boolean;
    closeWindow: (windowId: number) => boolean;
    setWindowPosition: (windowId: number, x: number, y: number) => boolean;
    setWindowDimensions: (windowId: number, width: number, height: number) => boolean;
    setWindowToBottom: (windowId: number) => boolean;
    setWindowToTop: (windowId: number) => boolean;
    setWindowToAlwaysOnTop: (windowId: number, shouldBeAlwaysOnTop: boolean) => boolean;
    getPixelColor: (x: number, y: number) => Color;
    takeScreenshotToFile: (x: number, y: number, width: number, height: number, filePath: string, scale: number) => string;
    takeWindowScreenshotToFile: (windowId: number, x: number, y: number, width: number, height: number, filePath: string, scale: number) => boolean;
    copyTextToClipboard: (text: string) => boolean;
    copyFileToClipboard: (filePath: string) => boolean;
    sleep: (milliseconds: number) => void;
    suppressInputEvents: (type: number, inputStateMap: Array<[number, Array<number>]>) => void;
    unsuppressInputEvents: (type: number, inputStateMap: Array<[number, Array<number>]>) => void;
    performOcrOnImage: (imagePath: string, language?: string) => string;
    getPixelColorsFromImage: (imagePath: string) => Uint8Array<number>; // each 6 values = x,y,r,g,b,a
    findImageTemplateMatches: (imagePath: string, subImagePath: string, minSimilarity: number) => Array<MatchRegion>;
    playSound: (audioPath: string, volume?: number, speed?: number, startTime?: number, endTime?: number) => { id: string, duration: number };
    pauseSound: (soundId: string) => void;
    resumeSound: (soundId: string) => void;
    stopSound: (soundId: string) => void;
    getSoundStatus: (soundId: string) => "playing" | "paused" | "stopped";
    getSoundTrackTime: (soundId: string) => number;
    setSoundTrackTime: (soundId: string, timestamp: number) => void;
    getSoundVolume: () => number;
    setSoundVolume: (volume: number) => void;
    getSoundSpeed: (soundId: string) => number;
    setSoundSpeed: (soundId: string, speed: number) => void;
    textToSpeech: (text: string, volume: number, speed: number, voice: string) => Promise<void>;
    createTrayIcon: (tooltip: string, iconPath: string) => number;
    removeTrayIcon: (windowId: number) => void;
    updateTrayIcon: (windowId: number, iconPath: string) => void;
    updateTrayIconTooltip: (windowId: number, tooltip: string) => void;
    addTrayIconMenuItem: (windowId: number, itemId: number, position: number, label: string, onClick: Function) => void;
    updateTrayIconMenuItemLabel: (windowId: number, itemId: number, label: string) => void;
    updateTrayIconMenuItemCallback: (windowId: number, itemId: number, onClick: Function) => void;
    removeTrayIconMenuItem: (windowId: number, itemId: number) => void;
  };
  export = value;
}
