import path from "node:path";
let nativeAddon: typeof import("@napi/actionify");

try {
  nativeAddon = require('../../../build/Release/actionify.node');
} catch (error: any) {
  throw new Error([
    ``,
    `==========================================`,
    `\x1b[31mFailed to load Actionify's native addon module.\x1b[0m`,
    ``,
    `Run \x1b[96mnpx actionify postinstall\x1b[0m in your terminal and try again.`,
    `==========================================`,
    `\x1b[90mDetails:\x1b[0m`,
    `  \x1b[90m• Required native addon module is missing or corrupted at: ${path.join(__dirname, "../../../build/Release/actionify.node")}\x1b[0m`,
    `  \x1b[90m• Raw error: ${(error?.message || String(error)).split("\n")[0]}\x1b[0m`,
  ].join("\n"));
}

const {
  getCursorPos,
  setCursorPos,
  leftClickDown,
  leftClickUp,
  rightClickDown,
  rightClickUp,
  mouseWheelScrollDown,
  mouseWheelScrollUp,
  mouseWheelPressDown,
  mouseWheelPressUp,
  mouseExtraButtonDown,
  mouseExtraButtonUp,
  keyPressDown,
  keyPressUp,
  typeUnicodeCharacter,
  getAvailableScreens,
  startInputEventListener,
  stopInputEventListener,
  startWindowEventListener,
  stopWindowEventListener,
  cleanResources,
  listWindows,
  getWindowById,
  focusWindow,
  restoreWindow,
  minimizeWindow,
  maximizeWindow,
  closeWindow,
  setWindowPosition,
  setWindowDimensions,
  setWindowToBottom,
  setWindowToTop,
  setWindowToAlwaysOnTop,
  getPixelColor,
  takeScreenshotToFile,
  takeWindowScreenshotToFile,
  copyTextToClipboard,
  copyFileToClipboard,
  sleep,
  suppressInputEvents,
  unsuppressInputEvents,
  performOcrOnImage,
  getPixelColorsFromImage,
  findImageTemplateMatches,
  playSound,
  pauseSound,
  resumeSound,
  stopSound,
  getSoundStatus,
  getSoundTrackTime,
  setSoundTrackTime,
  getSoundVolume,
  setSoundVolume,
  getSoundSpeed,
  setSoundSpeed,
  textToSpeech,
  createTrayIcon,
  removeTrayIcon,
  updateTrayIcon,
  updateTrayIconTooltip,
  addTrayIconMenuItem,
  updateTrayIconMenuItemLabel,
  updateTrayIconMenuItemCallback,
  removeTrayIconMenuItem,
} = nativeAddon;

export {
  getCursorPos,
  setCursorPos,
  leftClickDown,
  leftClickUp,
  rightClickDown,
  rightClickUp,
  mouseWheelScrollDown,
  mouseWheelScrollUp,
  mouseWheelPressDown,
  mouseWheelPressUp,
  mouseExtraButtonDown,
  mouseExtraButtonUp,
  keyPressDown,
  keyPressUp,
  typeUnicodeCharacter,
  getAvailableScreens,
  startInputEventListener,
  stopInputEventListener,
  startWindowEventListener,
  stopWindowEventListener,
  cleanResources,
  listWindows,
  getWindowById,
  focusWindow,
  restoreWindow,
  minimizeWindow,
  maximizeWindow,
  closeWindow,
  setWindowPosition,
  setWindowDimensions,
  setWindowToBottom,
  setWindowToTop,
  setWindowToAlwaysOnTop,
  getPixelColor,
  takeScreenshotToFile,
  takeWindowScreenshotToFile,
  copyTextToClipboard,
  copyFileToClipboard,
  sleep,
  suppressInputEvents,
  unsuppressInputEvents,
  performOcrOnImage,
  getPixelColorsFromImage,
  findImageTemplateMatches,
  playSound,
  pauseSound,
  resumeSound,
  stopSound,
  getSoundStatus,
  getSoundTrackTime,
  setSoundTrackTime,
  getSoundVolume,
  setSoundVolume,
  getSoundSpeed,
  setSoundSpeed,
  textToSpeech,
  createTrayIcon,
  removeTrayIcon,
  updateTrayIcon,
  updateTrayIconTooltip,
  addTrayIconMenuItem,
  updateTrayIconMenuItemLabel,
  updateTrayIconMenuItemCallback,
  removeTrayIconMenuItem,
};
